# Generated by Django 4.1.2 on 2022-10-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_api", "0008_mailmessage_subscribers"),
    ]

    operations = [
        migrations.DeleteModel(name="Comment",),
        migrations.DeleteModel(name="SubscribedUsers",),
    ]
