# Generated by Django 4.1.2 on 2022-10-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_api", "0009_delete_comment_delete_subscribedusers"),
    ]

    operations = [
        migrations.RemoveField(model_name="subscribers", name="date",),
    ]
