# Generated by Django 4.1.2 on 2022-10-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_api", "0010_remove_subscribers_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=158)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
    ]
